# Generated by Django 3.2.2 on 2021-06-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210626_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(0, 'Clothes'), (1, 'Accessories'), (2, 'Cooking Utilities'), (3, 'Electric Appliances'), (4, 'Gaming'), (5, 'Sports')]),
        ),
    ]
