# Generated by Django 3.2.2 on 2021-07-04 13:43

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_original_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_name_76a8ee_gin',
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='products_pr_name_bd81f1_gin'),
        ),
    ]
